from typing import Protocol, runtime_checkable
from ..models.progress import ProgressRecord


@runtime_checkable
class ProgressStore(Protocol):
    async def init(self, note_id: str) -> None: ...
    async def update(self, note_id: str, progress: int, step: str) -> None: ...
    async def finish(self, note_id: str) -> None: ...
    async def fail(self, note_id: str, error: str) -> None: ...
    async def get(self, note_id: str) -> ProgressRecord | None: ...
